# Generated by Django 5.2.5 on 2025-08-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primeline_web_app', '0005_category_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
